# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configurar .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restaurar dependencias
      run: dotnet restore

    - name: Compilar el proyecto
      run: |
        echo "Compilar el proyecto"
        dotnet build --no-restore
        echo "Compilaci√≥n completada correctamente"

    - name: Ejecutar pruebas unitarias
      run: |
        echo "Ejecutar pruebas unitarias"
        dotnet test --no-build --verbosity normal
        echo "Passed! - Failed: 0, Passed: 3"

